- name: Import key EPEL repository
  ansible.builtin.rpm_key:
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
    state: present

- name: Add EPEL repository
  ansible.builtin.dnf:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
    state: present

- name: Install EPEL packages
  ansible.builtin.dnf:
    name:
      - htop
      - keepassxc
      - pwgen
      - unrar
    state: present